services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/animes
    depends_on:
      - mongo
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
  mongo:
    image: mongo:4.4  # <-- Cambia esto de "mongo" a "mongo:4.4"
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:

